# Generated by Django 5.1.7 on 2025-06-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('github', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
            ],
        ),
    ]
