# Generated by Django 5.1.7 on 2025-06-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.TextField(blank=True),
        ),
    ]
